"""Storage abstraction.

The application only ever talks to :class:`StorageBackend`. Keys are generated by
the server (UUID-based), never derived from user input, and each backend still
validates them defensively. Local filesystem and S3-compatible object storage
are provided; switching is a configuration change (STORAGE_BACKEND).
"""

from __future__ import annotations

import re
from abc import ABC, abstractmethod
from dataclasses import dataclass

_KEY_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*(/[A-Za-z0-9][A-Za-z0-9._-]*)*$")

CONTENT_TYPES = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
    ".pdf": "application/pdf",
    ".json": "application/json",
}


class StorageError(Exception):
    pass


class InvalidKeyError(StorageError):
    pass


class ObjectNotFoundError(StorageError):
    pass


def validate_key(key: str) -> str:
    """Accept only relative, normalised keys made of safe characters."""
    if len(key) > 512 or not _KEY_PATTERN.match(key) or ".." in key.split("/"):
        raise InvalidKeyError(f"invalid storage key: {key!r}")
    return key


def content_type_for(key: str) -> str:
    dot = key.rfind(".")
    return (
        CONTENT_TYPES.get(key[dot:].lower(), "application/octet-stream")
        if dot != -1
        else "application/octet-stream"
    )


@dataclass(frozen=True, slots=True)
class StoredObject:
    key: str
    size: int
    content_type: str


class StorageBackend(ABC):
    """Minimal blocking interface; call through ``anyio.to_thread`` from async code."""

    name: str

    @abstractmethod
    def put(self, key: str, data: bytes, content_type: str | None = None) -> StoredObject: ...

    @abstractmethod
    def get(self, key: str) -> bytes: ...

    @abstractmethod
    def delete(self, key: str) -> None: ...

    @abstractmethod
    def delete_prefix(self, prefix: str) -> int: ...

    @abstractmethod
    def exists(self, key: str) -> bool: ...

    @abstractmethod
    def healthcheck(self) -> bool: ...
