"""Initial schema: users, refresh_tokens, model_versions, analyses, predictions, prediction_scores.

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 19:17:24.075093+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('architecture', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('weights_sha256', sa.String(length=64), nullable=False),
    sa.Column('trained', sa.Boolean(), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=False),
    sa.Column('num_classes', sa.Integer(), nullable=False),
    sa.Column('classes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preprocessing_version', sa.String(length=16), nullable=False),
    sa.Column('input_size', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('gradcam_layer', sa.String(length=64), nullable=False),
    sa.Column('trained_at', sa.String(length=40), nullable=True),
    sa.Column('card', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('weights_sha256', name=op.f('uq_model_versions_weights_sha256'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_table('analyses',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=False),
    sa.Column('image_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.Column('source_format', sa.String(length=10), nullable=False),
    sa.Column('source_width', sa.Integer(), nullable=False),
    sa.Column('source_height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('quality', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_analyses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_index('ix_analyses_user_created', 'analyses', ['user_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('predictions',
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=False),
    sa.Column('predicted_class_index', sa.Integer(), nullable=False),
    sa.Column('predicted_class_code', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('normalized_entropy', sa.Float(), nullable=False),
    sa.Column('concern_probability', sa.Float(), nullable=False),
    sa.Column('uncertain', sa.Boolean(), nullable=False),
    sa.Column('uncertainty_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('inference_ms', sa.Float(), nullable=False),
    sa.Column('gradcam_status', sa.String(length=16), nullable=False),
    sa.Column('gradcam_target_index', sa.Integer(), nullable=True),
    sa.Column('gradcam_raw_max', sa.Float(), nullable=True),
    sa.Column('explain_ms', sa.Float(), nullable=True),
    sa.Column('heatmap_key', sa.String(length=512), nullable=True),
    sa.Column('overlay_key', sa.String(length=512), nullable=True),
    sa.Column('cam_key', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("gradcam_status IN ('completed', 'failed', 'skipped')", name=op.f('ck_predictions_gradcam_status_valid')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_predictions_confidence_range')),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_predictions_analysis_id_analyses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_predictions_model_version_id_model_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index('ix_predictions_analysis_created', 'predictions', ['analysis_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_predictions_confidence'), 'predictions', ['confidence'], unique=False)
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_class_code'), 'predictions', ['predicted_class_code'], unique=False)
    op.create_table('prediction_scores',
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('class_index', sa.Integer(), nullable=False),
    sa.Column('class_code', sa.String(length=32), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.CheckConstraint('probability >= 0 AND probability <= 1', name=op.f('ck_prediction_scores_probability_range')),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_scores_prediction_id_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id', 'class_index', name=op.f('pk_prediction_scores')),
    sa.UniqueConstraint('prediction_id', 'class_code', name='uq_prediction_scores_prediction_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_scores')
    op.drop_index(op.f('ix_predictions_predicted_class_code'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_confidence'), table_name='predictions')
    op.drop_index('ix_predictions_analysis_created', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_analyses_user_created', table_name='analyses')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
